{
 "title": "Healthy Checks",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Postgre Healthy Check",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aspnetcore_healthcheck_status{name=\"Postgre Database\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mongo Healthy Check",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aspnetcore_healthcheck_status{name=\"Mongo Log\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Healthy Check",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aspnetcore_healthcheck_status{name=\"Redis Database\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}